# Generated by Django 4.0.3 on 2022-09-17 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0004_alter_job_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_archieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
