# Generated by Django 4.1.1 on 2022-09-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_job_is_archieved_job_people'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
